FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance

RUN pip install poetry
RUN apt-get -y update && apt-get install -y python3-dev g++ unixodbc-dev
RUN pip install --user pyodbc

# Add repository code
RUN mkdir -p /opt/dagster/dagster_home
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
WORKDIR $DAGSTER_HOME
ADD etl ./etl
COPY dagster.yaml .
COPY workspace.yaml .
COPY poetry.lock .
COPY pyproject.toml .
COPY run_dag.sh .
RUN chmod +x run_dag.sh

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["bash", "run_dag.sh"]
#CMD ["dagster", "api", "grpc", "--host", "0.0.0.0", "--port", "4000", "--package-name", "etl", "--working-directory", "/opt/dagster/app"]